### ISSUE TITLE
0.3.18 to 0.3.19 dependency issues

### ISSUE THREAD

**Issue by erik-sb** [machty/emblem.js#199]
Pulled the update from 0.3.18 to 0.3.19 indirectly via `gulp-ember-emblem`, seeing the following blocking exception being thrown:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
TypeError: Cannot read property 'original' of undefined
    at new AST.BlockNode (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/handlebars/dist/cjs/handlebars/compiler/ast.js:112:49)
    at peg$c34 (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:201:23)
    at peg$parsemustacheOrBlock (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:1552:20)
    at peg$parseexplicitMustache (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:1801:14)
    at peg$parsemustache (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:982:12)
    at peg$parsecontentStatement (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:829:18)
    at peg$parsestatement (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:807:16)
    at peg$parsecontent (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:780:12)
    at peg$parseinvertibleContent (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:642:12)
    at peg$parsestart (/home/nelsk/dev/bobbypin-web/bobbypin/web/node_modules/gulp-ember-emblem/node_modules/emblem/lib/parser.js:633:12)
```

Downgrading explicitly to 0.3.18 fixes the issue. Saw this brought in handlebars 2.0.0 up from 1.3.x, but I don't have time to delve further into this myself currently. Happy to provide more info if needed.

**Comment by BenjaminN** [comment]
Having the same issue on #200.

**Comment by tmosmant** [comment]
An easy temporary fix is to add a dependency to emblem 0.3.18 in your `package.json`.

**Comment by erik-sb** [comment]
@tmosmant thanks, that's actually what I ended up doing, 0.3.18 seems to be working fine. Not sure what's actually triggering this. Sounds like @BenjaminN thinks it has something do do with components, which we're using pretty extensively so that would make sense.

**Comment by machty** [comment]
0.3.19 should have been 0.4.0 because it depends on Handlebars 2. 0.3.18 is the last version dependent on Handlebars 1

**Comment by erik-sb** [comment]
Thanks @machty, appreciate the response.

**Comment by BenjaminN** [comment]
Just so you know @erik-sb, I [forked](https://github.com/BenjaminN/gulp-ember-emblem) [gulp-ember-emblem](https://github.com/wbyoung/gulp-ember-emblem) so it can work with the latest EmblemJS. I created a pull request but not sure @wbyoung is still working on gulp-ember-emblem.

Meanwhile, you can use mine by replacing `"gulp-ember-emblem": "0.1.1"` with `"gulp-ember-emblem": "git://github.com/BenjaminN/gulp-ember-emblem"` on your `package.json`.

It works well with **Ember 1.9.1** but doesn't work with the latest EmberJS because EmblemJS doesn't work with HTMLBars yet.
