### ISSUE TITLE
Command Line tool doesn't work

### ISSUE THREAD

**Issue by saponifi3d** [machty/emblem.js#233]
```bash
$ emblem test.emblem

module.js:340
    throw err;
          ^
Error: Cannot find module '../lib/emblem'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.16.0/v0.10.30/lib/node_modules/emblem/bin/emblem:107:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

This appears to be here: https://github.com/machty/emblem.js/blob/master/bin/emblem#L107

Some background, I'm trying to update `gulp-emblem` to the latest version, however it used the `precompile`method before which appears to now be deprecated.  I basically need this functionality back: https://github.com/machty/emblem.js/blob/master/bin/emblem#L165 and was trying to reproduce it.... should i simply us something like `Emblem.default.compile( emblem )` then send that to `Handlebars.precompile`?

**Comment by mixonic** [comment]
@saponifi3d they command line tools is definitely broken, re: https://github.com/machty/emblem.js/issues/213

The path indeed is to call the Emblem compiler, then pass it to the Ember HTMBars compiler. In the ember-cli addon:

* [fetch](https://github.com/Vestorly/ember-cli-emblem/blob/master/index.js#L17) and then [call](https://github.com/Vestorly/ember-cli-emblem/blob/master/index.js#L26) the emblem compiler
* Then the output of this (an HTMLBars template) is passed to the [ember-template-compiler](http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html#toc_ember-1-10). Usage is described on that link.

Let me know if you need any more context to get the gulp lib updated, and please PR an update to the README here when you finish :-)
