### ISSUE TITLE
Packaged 0.6.0 on NPM is Broken

### ISSUE THREAD

**Issue by atsjj** [machty/emblem.js#244]
The tarball on NPM doesn't contain the `dist` path causing it to break.

http://registry.npmjs.org/emblem/-/emblem-0.6.0.tgz

Likely a waste, but here's the error:
```
Cannot find module 'emblem'
Error: Cannot find module 'emblem'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at new TemplateCompiler (/path/to/my/project/node_modules/ember-cli-emblem/index.js:19:49)
    at TemplateCompiler (/path/to/my/project/node_modules/ember-cli-emblem/index.js:11:12)
    at Object.compiler.toTree (/path/to/my/project/node_modules/ember-cli-emblem/index.js:55:16)
    at /path/to/my/project/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:186:26
    at Array.forEach (native)
    at processPlugins (/path/to/my/project/node_modules/ember-cli/node_modules/ember-cli-preprocess-registry/preprocessors.js:184:11)
```

**Comment by machty** [comment]
Sorry, can you try 0.6.1 and let me know if you run into any issues?

**Comment by atsjj** [comment]
Sweet, looks like it's fixed!

Thanks!
